### ISSUE TITLE
Roadmap Next

### ISSUE THREAD

**Issue by goodmind** [goodmind/cycle-telegram#20]
## General
- [x] Remove lib from git
- [x] Update dependencies
- New events: 
  - [x] `channel_post`
    - [x] Tests
  - [x] `edited_channel_post`
    - [x] Tests
  - [x] `edited_message`
    - [x] Tests

## Types
 - [x] Runtime type checking of responses (possibly breaking change?)
   - [x] Tests
