### ISSUE TITLE
Plugins Roadmap

### ISSUE THREAD

**Issue by goodmind** [goodmind/cycle-telegram#9]
## Plugins
- [x] Rewrite plugins with Cycle Components
- [x] Arguments for plugins _kinda works_
- [x] Execute all plugins with matched regex (discuss #6) (done in 121d3e3d1f89d5fc8135108571ddb4feade93ef9)
- [x] Stream agnostic
- [x] Match type of `Plugin` (#24)
- [x] Plugins typings for streams

**Comment by goodmind** [comment]
I don't want to do this
